"""create enrollment_facts and course_facts tables

Revision ID: b0cfe485a0d3
Revises: 
Create Date: 2026-06-19 12:52:01.127456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0cfe485a0d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_facts',
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('instructor_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('enrollment_facts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enrollment_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('course_title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_facts_course_id'), 'enrollment_facts', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollment_facts_enrollment_id'), 'enrollment_facts', ['enrollment_id'], unique=True)
    op.create_index(op.f('ix_enrollment_facts_student_id'), 'enrollment_facts', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollment_facts_student_id'), table_name='enrollment_facts')
    op.drop_index(op.f('ix_enrollment_facts_enrollment_id'), table_name='enrollment_facts')
    op.drop_index(op.f('ix_enrollment_facts_course_id'), table_name='enrollment_facts')
    op.drop_table('enrollment_facts')
    op.drop_table('course_facts')
    # ### end Alembic commands ###
