services:

  gateway:
    build: services/gateway
    container_name: smartcourse_gateway
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      SERVICE_NAME: gateway
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      CERTIFICATE_URL: http://smartcourse_certificate:8000
      ANALYTICS_URL: http://smartcourse_analytics:8000
