services:

  gateway:
    build: .
    container_name: smartcourse_gateway
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      SERVICE_NAME: gateway
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      MONOLITH_URL: http://host.docker.internal:8000
      TEMPLATE_URL: http://smartcourse_template:8000
