"""add ondelete constraints to foreign keys

Revision ID: f17847dc8c52
Revises: c7a13d4f9b2e
Create Date: 2026-06-08 16:23:49.668860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f17847dc8c52'
down_revision: Union[str, Sequence[str], None] = 'c7a13d4f9b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('courses_instructor_id_fkey'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'users', ['instructor_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('enrollments_course_id_fkey'), 'enrollments', type_='foreignkey')
    op.drop_constraint(op.f('enrollments_student_id_fkey'), 'enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'enrollments', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'enrollments', 'users', ['student_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('lesson_completions_lesson_id_fkey'), 'lesson_completions', type_='foreignkey')
    op.drop_constraint(op.f('lesson_completions_student_id_fkey'), 'lesson_completions', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_completions', 'users', ['student_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'lesson_completions', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('lessons_module_id_fkey'), 'lessons', type_='foreignkey')
    op.create_foreign_key(None, 'lessons', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('modules_course_id_fkey'), 'modules', type_='foreignkey')
    op.create_foreign_key(None, 'modules', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.create_foreign_key(op.f('modules_course_id_fkey'), 'modules', 'courses', ['course_id'], ['id'])
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.create_foreign_key(op.f('lessons_module_id_fkey'), 'lessons', 'modules', ['module_id'], ['id'])
    op.drop_constraint(None, 'lesson_completions', type_='foreignkey')
    op.drop_constraint(None, 'lesson_completions', type_='foreignkey')
    op.create_foreign_key(op.f('lesson_completions_student_id_fkey'), 'lesson_completions', 'users', ['student_id'], ['id'])
    op.create_foreign_key(op.f('lesson_completions_lesson_id_fkey'), 'lesson_completions', 'lessons', ['lesson_id'], ['id'])
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.create_foreign_key(op.f('enrollments_student_id_fkey'), 'enrollments', 'users', ['student_id'], ['id'])
    op.create_foreign_key(op.f('enrollments_course_id_fkey'), 'enrollments', 'courses', ['course_id'], ['id'])
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_instructor_id_fkey'), 'courses', 'users', ['instructor_id'], ['id'])
    # ### end Alembic commands ###
